#Whether to log the dirt block on common setup
logDirtBlock = true
#A magic number
# Default: 42
# Range: > 0
magicNumber = 42
#What you want the introduction message to be for the magic number
magicNumberIntroduction = "The magic number is... "
# 
#A list of items that can use on side of terracotta golem.
#You can add other item to this list, it's texture must named be the same as item id.
items = ["minecraft:iron_ingot"]
#Whether to enable the health value display override for the weak potion effect
useWeakPoisonOverLay = true
#The number of #ancient_boat_need_1 that need to be held in hand to repair the ancient boat.
# Default: 5
# Range: 0 ~ 32767
"count of [ancient_boat_need_1]" = 5
#The number of #ancient_boat_need_2 that need to be held in hand to repair the ancient boat.
# Default: 2
# Range: 0 ~ 32767
"count of [ancient_boat_need_2]" = 2
#The number of #ancient_chest_boat_need_1 that need to be held in hand to repair the ancient chest boat.
# Default: 5
# Range: 0 ~ 32767
"count of [ancient_chest_boat_need_1]" = 5
#The number of #ancient_chest_boat_need_2 that need to be held in hand to repair the ancient chest boat.
# Default: 1
# Range: 0 ~ 32767
"count of [ancient_chest_boat_need_2]" = 1
# 
#Greatly enhance effects and monsters. Use for that games using mods with additional cultivation content- such as Curios, any Skill mods or Guns mods.
#true: Always enabled this mode.
#default: Automatically determine whether to enable it based on the player's combat performance.
#false: Never enabled this mode.
powerBattleMode = "default"
#After opening, you can right-click to harvest the crops of the module
rightClickHarvest = true
#After being turned off, when the Power Battle Mode is enabled, the prompt field will no longer be displayed in the game
powerBattleModeHint = true
# 
#We apologize for making players excessively capable. 
#For the sake of balance, you can use this option to synchronously strengthen some of the original enemies.
#Configure which enemies can be strengthened in the entity tags file, to all the functions.
needStrengthenTheEnemies = false
# 
#Configures whether to ignore the entity's potion effect immunity when the stun effect derives other potion effects.
#This allows stun to have a more consistent effect on different mobs.
useBetterStun = true
#Set the probability of the sniffer beast mining Mod items
# Default: 0.5
# Range: 0.0 ~ 1.0
mininProbability = 0.5
#The number of infernal forging effect's attribute will × this.
# Default: 1
# Range: 0 ~ 32767
"infernal forging attribute multiplier" = 1

[ReverseNormalEffect]
	#Potion effects that can be reversed. Effect in this Map will be remove every tick. 
	#It does not prevent the application of effects, so it may not completely block the activation of harmful potion effects sometimes if only use this.
	#"input-effect-n" means ID of the effect to be converted,"output-effect-n" means ID of the effect that conversion result.
	#Format: [["input-effect-1", "output-effect-1"], ["input-effect-2", "output-effect-2"], ...etc]
	reverseNormalEffect = [["minecraft:bad_omen", "minecraft:hero_of_the_village"], ["minecraft:unluck", "minecraft:luck"], ["minecraft:glowing", "minecraft:invisibility"], ["minecraft:slowness", "minecraft:speed"], ["minecraft:levitation", "minecraft:slow_falling"], ["minecraft:darkness", "minecraft:conduit_power"], ["minecraft:mining_fatigue", "minecraft:haste"], ["minecraft:weakness", "minecraft:strength"], ["minecraft:poison", "immortalers_delight:lingering_infusion"], ["minecraft:hunger", "immortalers_delight:satiated"], ["minecraft:wither", "immortalers_delight:vitality"], ["minecraft:nausea", "farmersdelight:nourishment"], ["minecraft:blindness", "minecraft:night_vision"], ["immortalers_delight:weak_poison", "farmersdelight:comfort"], ["immortalers_delight:weak_wither", "minecraft:regeneration"], ["twilightforest:frosty", "immortalers_delight:cool"], ["aether:inebriation", "aether:remedy"]]

[ReverseInstantEffect]
	#It takes effect when the effect in this Map is being applied, blocking its application and reversing it.
	#It only takes effect when the effect is being added, so it alone cannot convert existing effects.
	#"input-effect-n" means ID of the effect to be converted,"output-effect-n" means ID of the effect that conversion result.
	#Format: [["input-effect-1", "output-effect-1"], ["input-effect-2", "output-effect-2"], ...etc]
	reverseInstantEffect = [["minecraft:instant_damage", "minecraft:instant_health"], ["minecraft:blindness", "minecraft:night_vision"]]

[EffectsUsingLinearGrowth]
	#Determine which potion effects use linear growth.
	#Each entry should include a string representing the effect ID, along with two numbers,
	#the numbers will serving as the additiveTermA and multiplicativeTermB of the growth function respectively.
	#The final effective level of the potion effect is "A + level × B", where level is the original level of the effect — that is, the level entered when obtaining it via commands.
	#If an effect does not appear in any of the three lists, it will take effect according to the rules in this list by default.
	#Format: [["effect-id-1", additive-term-A, multiplicative-term-B], ["effect-id-2", additive-term-A, multiplicative-term-B], ...etc]
	effectsUsingLinearGrowth = [["immortalers_delight:vulnerable", 0, 0.5], ["immortalers_delight:relieve_poison", 1, 1]]

[EffectsUsingClassicalHarmonicSeriesGrowth]
	#Determine which potion effects use linear growth.
	#Each entry should include a string representing the effect ID, along with two numbers,
	#the numbers will serving as the additiveTermA and multiplicativeTermB of the growth function respectively.
	#The final effective level of the potion effect is "A + level × B", 
	#The level is calculated using the classic harmonic series. For effects with amplifier = 1 to 4, the values are 1, 1.5, 1.833, and 2.083 respectively.
	#Format: [["effect-id-1", additive-term-A, multiplicative-term-B], ["effect-id-2", additive-term-A, multiplicative-term-B], ...etc]
	effectsUsingClassicalHarmonicSeriesGrowth = [["immortalers_delight:gas_poison", 0, 1], ["immortalers_delight:inebriated", 0, 1], ["immortalers_delight:vitality", 0, 1]]

[EffectsUsingGradualHarmonicSeriesGrowth]
	#Determine which potion effects use linear growth.
	#Each entry should include a string representing the effect ID, along with two numbers,
	#the numbers will serving as the additiveTermA and multiplicativeTermB of the growth function respectively.
	#The final effective level of the potion effect is "A + level × B",
	#The level is calculated using a gentle harmonic series. For effects with amplifier values from 1 to 10, the corresponding values are 1, 1.5, 2, 2.333, 2.666, 3, 3.25, 3.5, 3.75, and 4 respectively.
	#Format: [["effect-id-1", additive-term-A, multiplicative-term-B], ["effect-id-2", additive-term-A, multiplicative-term-B], ...etc]
	effectsUsingGradualHarmonicSeriesGrowth = [["immortalers_delight:prehistoric_powers", -0.5, 1.5], ["immortalers_delight:resistance_to_undead", 0, 1], ["immortalers_delight:resistance_to_arthropod", 0, 1], ["immortalers_delight:resistance_to_abyssal", 0, 1], ["immortalers_delight:resistance_to_illager", 0, 1], ["immortalers_delight:warm_current_surges", 0, 1], ["immortalers_delight:lingering_infusion", 0, 1], ["immortalers_delight:deepness", 0, 1], ["immortalers_delight:let_it_freeze", 0, 1], ["immortalers_delight:moon_bright", 0, 1]]

[MobDynamicDamage]
	#Configure the attack damage multiplier of powered mobs be increased based on the target's health value.
	#If use, it will make damage become (1 + the value) * old damage.
	#the numbers will be stored as a growth factor A and an upper limit B.
	#The damage multiplier will increase by A per point of the target's health until it reaches B.
	#This configuration option only takes effect when the needStrengthenTheEnemies option is enabled.
	#Format: [["mob_or_tag-id-1", growth-factor-A, upper-limit-B], ["mob_or_tag-id-2", growth-factor-A, upper-limit-B], ...etc]
	mobDynamicDamage = [["#immortalers_delight:normal_mobs", 0, 1], ["#immortalers_delight:elite_mobs", 0.002, 1.5], ["#immortalers_delight:mid_boss", 0.006, 3], ["twilightforest:minoshroom", 0.02, 6]]

[MobMinDamage]
	#Configure the min value when powered mobs attack.
	#If use, it will make the damage have a min value when powered mobs attack, even if you have the [Resistance V].
	#the numbers will be stored as a percentage value A and an fixed value B.
	#The damage will increase by "A × target's maxHealth + B".
	#This configuration option only takes effect when the needStrengthenTheEnemies option is enabled.
	#Format: [["mob_or_tag-id-1", percentage-value-A, fixed-value-B], ["mob_or_tag-id-2", percentage-value-A, fixed-value-B], ...etc]
	mobMinDamage = [["#immortalers_delight:normal_mobs", 0, 1], ["#immortalers_delight:elite_mobs", 0, 2], ["#immortalers_delight:mid_boss", 0, 2.5], ["irons_spellbooks:dead_king", 0.03, 6]]

[MobHighDamageCounteraction]
	#Configure the damage multiplier taken by mobs will decrease as the base damage value increases.
	#If use, it will divide the damage taken by the powered mobs by a coefficient.
	#the numbers will be stored as a growth factor A and an upper limit B.
	#The damage divisor will increase by A per point of the damage value until it reaches B.
	#For example,if set upper limit 9.0 to a mob, damage taken by mobs will min become 0.1x if the damage high enough.
	#This configuration option only takes effect when the needStrengthenTheEnemies option is enabled.
	#Format: [["mob_or_tag-id-1", growth-factor-A, upper-limit-B], ["mob_or_tag-id-2", growth-factor-A, upper-limit-B], ...etc]
	mobHighDamageCounteraction = [["#immortalers_delight:normal_mobs", 0.08, 15], ["#immortalers_delight:elite_mobs", 0.05, 11], ["#immortalers_delight:mid_boss", 0.04, 7], ["goety:brood_mother", 0.1, 100]]
