[client]
	#A multiplier for how many particles emanate from dandies in general
	particleSpawnMultiplier = 1.0
	#A multiplier for how long particles last upon spawn
	particleLifetimeMultiplier = 1.0
	#Placing a stop_fluff_blocks block stops particles when placed up to this far below fluffy dandelions
	stopFluffDepth = 2
